str = ''
str += '<h2><span>정산관리</span></h2>' 
str += '<ul class="s_menu">' 
	str += '<li><a href="#">판매현황</a>' 
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">월별판매현황</a></li>'
			str += '<li><a href="#">일별판매현황</a></li>'
			str += '<li><a href="#">구매취소내역</a></li>'
		str += '</ul>' 
	str += '</li>' 
	str += '<li><a href="#">정산현황</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">당월정산현황</a></li>' 
			str += '<li><a href="#">영수증처리</a></li>' 
			str += '<li><a href="#">송금결과척리</a></li>' 
			str += '<li><a href="#">송금포기현황</a></li>' 
			str += '<li><a href="#">송금결과현황</a></li>'
		str += '</ul>' 
	str += '</li>' 
	str += '<li><a href="#">영수증관리</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">영수증발행관리</a></li>' 
			str += '<li><a href="#">당첨영수증관리</a></li>' 
		str += '</ul>' 
	str += '</li>'
	str += '<li><a href="#">정산환율관리</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">정산환율관리</a></li>'
		str += '</ul>' 
	str += '</li>'
	str += '<li><a href="#">폰빌결제관리</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">폰빌결제관리</a></li>'
		str += '</ul>' 
	str += '</li>'
str += '</ul> ' 

document.write(str)