str = ''
str += '<h2><span>상품관리</span></h2>' 
str += '<ul class="s_menu">' 
	str += '<li><a href="#">상품관리</a>' 
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">상품정보</a></li>' 
		str += '</ul>' 
	str += '</li>' 
	str += '<li><a href="#">검증관리</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">검증현황</a></li>' 
			str += '<li><a href="#">Application조회</a></li>' 
			str += '<li><a href="#">Test 할당</a></li>' 
			str += '<li><a href="#">Test List</a></li>' 
			str += '<li><a href="#">Test 승인</a></li>' 
			str += '<li><a href="#">Test 항목 관리</a></li>' 
		str += '</ul>' 
	str += '</li>' 
	str += '<li><a href="#">캐쉬관리</a>'  
		str += '<ul class="n_menu">' 
			str += '<li><a href="#">회원별 T store Cash 내역</a></li>' 
			str += '<li><a href="#">충전내역</a></li>' 
			str += '<li><a href="#">취소내역</a></li>' 
			str += '<li><a href="#">운영자 캐쉬 발급 내역</a></li>' 
			str += '<li><a href="#">기프트카드 내역</a></li>' 
		str += '</ul>' 
	str += '</li>'
str += '</ul> ' 

document.write(str)