str = ''
str += '<div class="paging_area">' 
str += '	<div class="paging">' 
str += '		<a href="#" class="arr"><img src="../images/board/arrL_02.gif" alt="firstpage" /></a><a href="#" class="arr"><img src="../images/board/arrL_01.gif" alt="prevpage" /></a>' 
str += '		<a href="#"><strong>1</strong></a>' 
str += '		|' 
str += '		<a href="#">2</a>' 
str += '		|' 
str += '		<a href="#">3</a>' 
str += '		|' 
str += '		<a href="#">4</a>' 
str += '		|' 
str += '		<a href="#">5</a>' 
str += '		<a href="#" class="arr"><img src="../images/board/arrR_01.gif" alt="nextpage" /></a><a href="#" class="arr"><img src="../images/board/arrR_02.gif" alt="lastpage" /></a>' 
str += '	</div>' 
str += '</div>' 
document.write(str)