str = ''
str += '<h1 class="logo"><img src="../images/top_logo.gif" alt="" /></h1>' 
str += '<div class="admin_info">' 
	str += '<span>관리자 <strong>슈퍼관리자</strong>님</span>			' 
	str += '<span class="time">최종 접속일 : 2011-02-18 13:01:47.0</span>' 
str += '</div>' 
str += '<ul class="gnb">' 
	str += '<li class="no_bg"><a href="#">회원관리</a></li>' 
	str += '<li><a href="#">컨텐츠관리</a></li>' 
	str += '<li><a href="#">고객지원</a></li>' 
	str += '<li><a href="#">기술지원</a></li>' 
	str += '<li><a href="#">상품정산관리</a></li>' 
	str += '<li><a href="#">통계관리</a></li>' 
	str += '<li><a href="#">운영자관리</a></li>' 
	str += '<li><a href="#">BP관리</a></li>' 
	str += '<li><a href="#">단말기POC관리</a></li>' 
str += '</ul>' 

document.write(str)